import tkinter
from course import get_course
print(get_course('R01235'))
window =tkinter.Tk()
window.geometry('600x500')
window.title('Курс валют')
img_logo = tkinter.PhotoImage(file ='C:/Users/adm/Desktop/project/pythonlessons/6ypok/logo.png')
logo = tkinter.Label(image=img_logo)
logo.place(x=0,y =0)
lab = tkinter.Label(text='Курс валют \n Maximum bank', fg='black', font='Arial 22')
lab.place(x=300,y=35)
usd_course=tkinter.Label(text=f"$ {get_course('R01235')}", font = 'Arial 22')
usd_course.place(x=90,y=150)
euro_course=tkinter.Label(text=f"€ {get_course('R01239')}", font = 'Arial 22')
euro_course.place(x=90,y=190)
window.mainloop()